### ISSUE TITLE
Failing on two column spectrum file

### ISSUE THREAD

**Issue by guillochon** [daniel-muthukrishna/DASH#2]
Tried out this one: https://raw.githubusercontent.com/astrocatalogs/sne-external-spectra/master/CfA_SNIbc/sn1998dt/sn1998dt-19980919.flm

Which is at a redshift of 0.0153. I had installed the latest version into a fresh Python 2.7 environment via `python setup.py install`.

My test.py:
```Python
import dash

classification = dash.Classify(["/path/to/sn1998dt-19980919.flm"], [0.0153])
print(classification.list_best_matches(n=1))
```

The error:
```bash
Invalid Input File
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(classification.list_best_matches(n=1))
  File "/Users/james/miniconda3/envs/py27/lib/python2.7/site-packages/dash/classify.py", line 58, in list_best_matches
    bestTypes, softmaxes = self._input_spectra_info()
  File "/Users/james/miniconda3/envs/py27/lib/python2.7/site-packages/dash/classify.py", line 48, in _input_spectra_info
    inputImage, typeNamesList, nw, nBins = self._get_images(f, z, trainParams)
  File "/Users/james/miniconda3/envs/py27/lib/python2.7/site-packages/dash/classify.py", line 36, in _get_images
    loadInputSpectra = LoadInputSpectra(filename, redshift, redshift, self.smooth, trainParams)
  File "/Users/james/miniconda3/envs/py27/lib/python2.7/site-packages/dash/restore_model.py", line 43, in __init__
    self.inputImages, self.inputFilenames, self.inputRedshifts, self.typeNamesList = self.inputSpectra.redshifting()
  File "/Users/james/miniconda3/envs/py27/lib/python2.7/site-packages/dash/input_spectra.py", line 38, in redshifting
    tempwave, tempflux, tminindex, tmaxindex = readSpectra.input_spectrum(z, self.smooth)
  File "/Users/james/miniconda3/envs/py27/lib/python2.7/site-packages/dash/create_arrays.py", line 137, in input_spectrum
    wave, flux, minIndex, maxIndex = self.data.two_column_data(z, smooth)
  File "/Users/james/miniconda3/envs/py27/lib/python2.7/site-packages/dash/sn_processing.py", line 44, in two_column_data
    self.wave, self.flux = self.spectrum
TypeError: 'int' object is not iterable
```

**Comment by daniel-muthukrishna** [comment]
I have made some changes. Hopefully this fixes your problem?
Try running  `pip install astrodash` to get the latest stable version.

I ran your file through DASH for fun: It looks like a Ib-norm at 18 to 26 days after max:

![image](https://cloud.githubusercontent.com/assets/17826840/23600965/3d4b3d5c-029d-11e7-9651-6a067755b97c.png)

**Comment by guillochon** [comment]
Yep, works for me now! And indeed, it's a Ib, just wanted to test it against a known event.

**Comment by daniel-muthukrishna** [comment]
Great to hear! Feel free to leave more suggestions as issues
